module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}'
  ],
  theme: {
    extend: {
      colors: {
        'background':                '#08090a',
        'surface':                   '#0c1321',
        'surface-dim':               '#0c1321',
        'surface-deep':              '#050B19',
        'surface-muted':             '#161B22',
        'surface-container-lowest':  '#070e1c',
        'surface-container-low':     '#151b2a',
        'surface-container':         '#191f2e',
        'surface-container-high':    '#232a39',
        'surface-container-highest': '#2e3544',
        'surface-bright':            '#333949',
        'border-subtle':             '#1f2128',
        'on-surface':                '#dce2f7',
        'on-surface-variant':        '#b9cbbd',
        'text-dim':                  '#8B949E',
        'primary':                   '#cdffdc',
        'primary-container':         '#00f59b',
        'on-primary':                '#003920',
        'on-primary-container':      '#006b41',
        'ai-glow':                   '#00F59B',
        'data-blue':                 '#3576DF',
        'data-orange':               '#F7931A',
        'secondary':                 '#adc6ff',
        'secondary-container':       '#005ac2',
        'on-secondary':              '#002e69',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'tertiary':                  '#fff2dc',
        'tertiary-container':        '#ffd165',
        'outline':                   '#849588',
        'outline-variant':           '#3b4a3f',
        'inverse-surface':           '#dce2f7',
        'inverse-on-surface':        '#2a3040',
      },
      fontFamily: {
        'sans': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        'ai-glow':  '0 0 12px 0 rgba(0, 245, 155, 0.15)',
        'nav-glow': '0 0 15px rgba(0, 245, 155, 0.3)',
      },
    },
  },
  plugins: [],
}
